function Hd = equiripple_low_pass
%EQUIRIPPLE_LOW_PASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
% Generated on: 07-Nov-2023 22:45:19

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N     = 191;     % Order
Fpass = 0.45;  % Passband Frequency
Fstop = 0.55;  % Stopband Frequency
Wpass = 1;     % Passband Weight
Wstop = 0.001;     % Stopband Weight
dens  = 100;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop 1], [1 1 0 0], [Wpass Wstop], {dens});
Hd = dfilt.dffir(b);

% [EOF]
